app = 'markov-generator-fedi'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

[http_service.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[mounts]]
  source = "markov_data"
  destination = "/data"

[env]
  PORT = "8888"
  DEBUG = "False"
